sudo: false
language: go
go:
- 1.6
script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/kisielk/errcheck
- go test -v -race
# disabling go vet test due to generated code
- go vet
- errcheck -ignoretests
- go test -coverprofile=profile.out -covermode=count
- goveralls -service=travis-ci -coverprofile=profile.out -repotoken $COVERALLS
notifications:
  email:
  - marty.schoch@gmail.com
